// Question database built from the supplied anatomy and physiology course materials.
const questionDatabase = [];
function addQuestions(topic, rows) {
  const existingCount = questionDatabase.filter((item) => item.topic === topic).length;
  rows.forEach(([question, options, answer, explanation], index) => {
    questionDatabase.push({ id: `${topic}-${String(existingCount + index + 1).padStart(2, '0')}`, topic, question, options: options.split('|'), answer, explanation });
  });
}

addQuestions('body', [
  ['Which level of organisation comes directly after tissues?', 'Atoms|Organs|Systems|Cells', 1, 'Tissues combine to form organs, which then work together in body systems.'],
  ['Which organelle produces most of the cell ATP?', 'Nucleus|Lysosome|Mitochondrion|Cell membrane', 2, 'Mitochondria convert energy from nutrients and oxygen into ATP.'],
  ['What does anatomy study?', 'Abnormal change|Body structure|Chemical energy only|Body temperature', 1, 'Anatomy is the study of body structure and how organs or body parts are constructed.'],
  ['What does physiology study?', 'How the body works|The names of bones only|Disease statistics|Cell colour', 0, 'Physiology explains how the body and its systems function.'],
  ['What is pathophysiology concerned with?', 'Normal sleep|Effects of illness and injury|Naming tissues|Normal exercise only', 1, 'Pathophysiology studies abnormal changes and the effects of illness or injury on the body.'],
  ['What is the smallest unit of life that can replicate?', 'Organ|Tissue|Cell|System', 2, 'Cells provide structure and are the smallest unit of life capable of replication.'],
  ['Which elements make up much of the body according to the introduction material?', 'Hydrogen, carbon, nitrogen and oxygen|Iron, gold, silver and copper|Calcium, lead, tin and zinc|Sodium, chlorine, iodine and fluorine', 0, 'The introduction highlights hydrogen, carbon, nitrogen and oxygen as major body elements.'],
  ['What do atoms combine to form?', 'Tissues only|Molecules or compounds|Organs directly|Blood vessels', 1, 'Atoms combine to form molecules or compounds such as water.'],
  ['What is the charge of a proton?', 'Negative|Neutral|Positive|Variable', 2, 'Protons have a positive charge; electrons are negative and neutrons neutral.'],
  ['What is the charge of an electron?', 'Positive|Negative|Neutral|Double positive', 1, 'Electrons carry a negative charge.'],
  ['What is the charge of a neutron?', 'Positive|Negative|Neutral|Alternating', 2, 'Neutrons have no electrical charge.'],
  ['What does the cell membrane do?', 'Stores bones|Controls what enters and leaves the cell|Produces speech|Pumps blood', 1, 'The cell membrane acts as a barrier and controls movement of substances into and out of the cell.'],
  ['What is found in the nucleus?', 'DNA|Bile|Haemoglobin only|Cerebrospinal fluid', 0, 'The nucleus contains DNA, the genetic instructions for development and function.'],
  ['What is the role of lysosomes?', 'Break down and recycle used components|Carry nerve impulses|Make the skeleton|Exchange lung gases', 0, 'Lysosomes are the cell recyclers and break down used components.'],
  ['What is ATP often described as?', 'The body battery|A protective bone|A nerve covering|A blood vessel', 0, 'ATP is a usable energy store often described as the body battery.'],
  ['What is metabolism?', 'The sum of chemical reactions in cells|The movement of bones|Only breathing|The skin surface', 0, 'Metabolism is the sum of chemical reactions that convert nutrients into energy and support cell function.'],
  ['Diffusion is movement from which concentration?', 'Low to high|High to low|Equal to higher only|No concentration', 1, 'Diffusion moves particles from a high concentration to a low concentration.'],
  ['What does osmosis describe?', 'Movement of water across a semi-permeable membrane|Movement of bones|Production of ATP|Movement of blood through arteries', 0, 'Osmosis is the movement of water across a semi-permeable membrane.'],
  ['Which tissue covers body surfaces and lines organs?', 'Muscle|Nervous|Epithelial|Adipose only', 2, 'Epithelial tissue covers the outside and inside surfaces of the body.'],
  ['Which is an example of connective tissue?', 'Bone|Neuron impulse|Epidermal surface only|Cardiac rhythm', 0, 'Connective tissue includes bone, cartilage, blood, adipose and lymphatic tissue.'],
  ['What is a key function of muscle tissue?', 'Create movement|Filter blood only|Store DNA|Make CSF', 0, 'Muscle cells contract to allow movement.'],
  ['What does nervous tissue do?', 'Detects information and carries impulses|Stores urine|Makes bile|Forms joints only', 0, 'Nervous tissue senses information and generates or conducts electrical impulses.'],
  ['What happens when tissues join together?', 'They form organs|They become atoms|They disappear|They form electrons', 0, 'Tissues combine to form organs with specialised functions.'],
  ['What happens when organs work together?', 'They form a body system|They become one cell|They become a molecule|They stop functioning', 0, 'Organs work together in systems with specific functions.'],
  ['Which system transports oxygen and nutrients in the blood?', 'Cardiovascular|Integumentary only|Reproductive only|Nervous only', 0, 'The cardiovascular system transports oxygen, nutrients and waste products.'],
  ['Which system is responsible for gas exchange?', 'Respiratory|Urinary|Lymphatic|Musculoskeletal', 0, 'The respiratory system brings in oxygen and removes carbon dioxide.'],
  ['Which system includes the brain and spinal cord?', 'Central nervous|Peripheral nervous only|Digestive|Integumentary', 0, 'The brain and spinal cord make up the central nervous system.'],
  ['Which system includes skin, hair and nails?', 'Integumentary|Respiratory|Cardiovascular|Lymphatic', 0, 'The integumentary system is the body outer layer and includes skin, hair and nails.'],
  ['What is the result of body systems working together?', 'They maintain life and normal function|They prevent all movement|They stop metabolism|They remove all cells', 0, 'Body systems are interdependent and work together to maintain life.'],
  ['Which process allows cells to use oxygen and nutrients to release energy?', 'Cellular respiration|Osmosis only|Blood clotting|Nerve conduction only', 0, 'Cellular respiration uses nutrients and oxygen to produce usable energy such as ATP.']
]);

addQuestions('cardiovascular', [
  ['What makes up the cardiovascular system?', 'Heart, blood and vessels|Brain, CSF and nerves|Lungs, bronchi and diaphragm|Kidneys, bladder and ureters', 0, 'The cardiovascular system consists of the heart, blood and blood vessels.'],
  ['What is the main pumping organ?', 'Liver|Heart|Spleen|Kidney', 1, 'The heart pumps blood around the body.'],
  ['Which chamber receives deoxygenated blood returning from the body?', 'Right atrium|Left atrium|Right ventricle|Left ventricle', 0, 'Deoxygenated blood returns to the right atrium.'],
  ['Which chamber pumps oxygenated blood into the systemic circulation?', 'Right atrium|Left atrium|Right ventricle|Left ventricle', 3, 'The left ventricle pumps oxygenated blood into the systemic circulation.'],
  ['Where does the right ventricle send blood?', 'To the lungs|To the brain directly|To the kidneys only|To the aorta', 0, 'The right ventricle sends deoxygenated blood through the pulmonary trunk to the lungs.'],
  ['Where does the left ventricle send blood?', 'To the lungs only|To the body through the aorta|To the right atrium|To the vena cava', 1, 'The left ventricle ejects oxygenated blood into the aorta for the body.'],
  ['Which vessels return blood to the heart?', 'Veins|Arteries|Capillaries only|Bronchi', 0, 'Veins carry blood back towards the heart.'],
  ['Which vessels carry blood away from the heart?', 'Veins|Arteries|Lymph vessels|Alveoli', 1, 'Arteries carry blood away from the heart.'],
  ['Where does exchange between blood and tissues mainly occur?', 'Capillaries|Aorta|Vena cava|Pulmonary trunk only', 0, 'Capillary walls provide a short exchange route between blood and tissues.'],
  ['Which vessel returns blood from the upper body?', 'Superior vena cava|Aorta|Pulmonary vein|Left coronary artery', 0, 'The superior vena cava returns blood from the upper body to the right atrium.'],
  ['Which vessel returns blood from the lower body?', 'Inferior vena cava|Pulmonary trunk|Aorta|Carotid artery', 0, 'The inferior vena cava returns blood from the lower body.'],
  ['Which vessel carries blood from the right ventricle to the lungs?', 'Pulmonary trunk|Aorta|Superior vena cava|Pulmonary vein', 0, 'The pulmonary trunk carries deoxygenated blood towards the lungs.'],
  ['Which vessels return oxygenated blood from the lungs?', 'Pulmonary veins|Pulmonary arteries|Venae cavae|Coronary arteries', 0, 'Pulmonary veins return oxygenated blood to the left atrium.'],
  ['Which chamber receives blood from the venae cavae?', 'Right atrium|Right ventricle|Left atrium|Left ventricle', 0, 'The venae cavae empty into the right atrium.'],
  ['Which chamber receives blood from pulmonary veins?', 'Right atrium|Right ventricle|Left atrium|Left ventricle', 2, 'Pulmonary veins empty oxygenated blood into the left atrium.'],
  ['What is the purpose of heart valves?', 'Keep blood moving in one direction|Make red cells|Exchange oxygen in the lungs|Control body temperature', 0, 'Valves prevent backflow and help maintain one-way blood flow.'],
  ['Which valve is between the right atrium and right ventricle?', 'Tricuspid valve|Mitral valve|Aortic valve|Pulmonary valve', 0, 'The tricuspid valve separates the right atrium and right ventricle.'],
  ['Which valve is between the left atrium and left ventricle?', 'Tricuspid valve|Mitral valve|Aortic valve|Pulmonary valve', 1, 'The mitral valve separates the left atrium and left ventricle.'],
  ['Which valve controls flow into the aorta?', 'Aortic valve|Mitral valve|Tricuspid valve|Pulmonary valve', 0, 'The aortic valve lies between the left ventricle and aorta.'],
  ['Which valve controls flow into the pulmonary trunk?', 'Aortic valve|Mitral valve|Tricuspid valve|Pulmonary valve', 3, 'The pulmonary valve lies between the right ventricle and pulmonary trunk.'],
  ['What does blood transport?', 'Oxygen, nutrients and waste|Only sound|Only nerve impulses|Only heat', 0, 'Blood transports oxygen, nutrients, hormones and waste products.'],
  ['Which is a function of the cardiovascular system?', 'Temperature regulation|Producing urine directly|Coordinating speech|Digesting food mechanically', 0, 'The cardiovascular system contributes to temperature regulation.'],
  ['How does the cardiovascular system support host defence?', 'Blood transports immune components around the body|The aortic valve destroys bacteria|The diaphragm produces antibodies|The spinal cord filters pathogens', 0, 'The cardiovascular system supports host defence through blood and immune components.'],
  ['Approximately how often does a resting heart beat according to the material?', '70 times per minute|7 times per hour|700 times per minute|Once per minute', 0, 'The introduction material gives around 70 beats per minute as a typical resting figure.'],
  ['What is the heart approximately the size of?', 'A clenched fist|A football|A kidney|A grain of rice', 0, 'The supplied material compares the heart to a clenched fist.'],
  ['What does deoxygenated blood do before returning to the left heart?', 'Passes through the lungs for gas exchange|Passes through the kidneys only|Enters the brain first|Leaves through the skin', 0, 'It travels to the lungs where gas exchange occurs before returning oxygenated to the left heart.'],
  ['Which artery supplies the heart muscle?', 'Coronary artery|Pulmonary vein|Vena cava|Carotid sinus only', 0, 'Coronary arteries supply the heart muscle itself.'],
  ['What does the aorta carry?', 'Oxygenated blood away from the left ventricle|Deoxygenated blood to the lungs|Blood into the right atrium|Lymph to the heart', 0, 'The aorta carries oxygenated blood from the left ventricle to the body.'],
  ['What can poor circulation affect?', 'Delivery of oxygen to tissues|Only hair colour|Only hearing|Only digestion of starch', 0, 'Circulation is essential for delivering oxygen and nutrients to tissues.'],
  ['Which finding should be treated as clinically important in a cardiovascular assessment?', 'Chest pain|Normal appetite|A healed small scratch|Clear speech after rest', 0, 'Chest pain can indicate a serious cardiovascular problem.']
]);

addQuestions('respiratory', [
  ['What is the main purpose of gas exchange?', 'Move oxygen into blood and carbon dioxide out|Make urine|Produce bone|Store glucose only', 0, 'Gas exchange brings oxygen into the blood and removes carbon dioxide.'],
  ['Which two routes can inspired air use to enter the respiratory tract?', 'The nasopharynx and mouth|The aorta and vena cava|The oesophagus and stomach|The bronchi and alveoli', 0, 'Air can enter through the nasopharynx or mouth before reaching the trachea.'],
  ['What does the trachea lead into?', 'The bronchial tree|The left ventricle|The spinal cord|The bladder', 0, 'The trachea divides into the bronchi and branching bronchial tree.'],
  ['What is the function of the bronchial tree?', 'Conduct air through branching airways|Pump blood|Filter urine|Control pupils', 0, 'The bronchial tree distributes air through the lungs.'],
  ['What is the role of the lungs?', 'Gas exchange|Produce CSF|Store bile|Make bones', 0, 'The lungs provide the main surface for respiratory gas exchange.'],
  ['What muscle helps change chest pressure for breathing?', 'Diaphragm|Biceps|Cerebellum|Cardiac valve', 0, 'The diaphragm contracts and relaxes to help move air in and out.'],
  ['What direction does oxygen move during pulmonary gas exchange?', 'From air into blood|From blood into air only|From bone into muscle|From urine into blood', 0, 'Oxygen diffuses from the air spaces into the blood.'],
  ['What direction does carbon dioxide move for exhalation?', 'From blood into the lungs|From lungs into blood only|From bone into air|From skin into stomach', 0, 'Carbon dioxide diffuses from blood into the lungs to be exhaled.'],
  ['What is diffusion?', 'Movement from high to low concentration|Movement from low to high only|Muscle contraction|Blood clotting', 0, 'Diffusion is movement down a concentration gradient.'],
  ['Which blood component carries oxygen around the body?', 'Red blood cells|Lymph|Cerebrospinal fluid|Urine', 0, 'Red blood cells carry oxygen around the body using haemoglobin.'],
  ['What waste gas is produced by cells?', 'Carbon dioxide|Oxygen|Nitrogen only|Hydrogen only', 0, 'Carbon dioxide is produced as a waste product of cellular respiration.'],
  ['What does cellular respiration help produce?', 'ATP|CSF|Bile only|Bone marrow only', 0, 'Cells use nutrients and oxygen to produce ATP.'],
  ['Which aspect of blood chemistry does the respiratory system help regulate?', 'Blood acidity|Bone length|Urine colour|Memory storage', 0, 'The respiratory system helps regulate blood acidity by removing carbon dioxide.'],
  ['What does the respiratory system filter?', 'Inspired air|Blood cells|CSF|Urine', 0, 'The airways filter inspired air before it reaches deeper lung structures.'],
  ['Which structure in the respiratory system helps produce vocal sounds?', 'The larynx|The alveoli|The diaphragm|The bronchioles', 0, 'The larynx contains the vocal cords and helps produce vocal sounds.'],
  ['Which sense has receptors in the respiratory system?', 'Smell|Balance only|Touch only|Hearing only', 0, 'The source material notes receptors providing a sense of smell.'],
  ['Where is the diaphragm located in relation to the lungs?', 'Below the lungs|Inside the brain|Above the trachea|Inside the heart', 0, 'The diaphragm forms the muscular floor of the thorax beneath the lungs.'],
  ['What happens when the diaphragm contracts?', 'Thoracic volume increases to draw air in|The heart stops|The airway closes|Blood becomes urine', 0, 'Contraction flattens the diaphragm and increases thoracic volume.'],
  ['What happens when the diaphragm relaxes?', 'Thoracic volume decreases and air can leave|The lungs fill with blood|The brain expands|The airway becomes bone', 0, 'Relaxation reduces thoracic volume and supports expiration.'],
  ['Which system transports oxygen after gas exchange?', 'Cardiovascular|Lymphatic|Reproductive|Integumentary', 0, 'The cardiovascular system distributes oxygenated blood to tissues.'],
  ['Which gas is breathed in for cellular use?', 'Oxygen|Carbon dioxide|Methane|Helium', 0, 'Oxygen is taken in and used by cells.'],
  ['Which gas is breathed out as a waste product?', 'Carbon dioxide|Oxygen only|Nitrogen only|Hydrogen', 0, 'Carbon dioxide is removed from the body in exhaled air.'],
  ['What can airway narrowing affect?', 'Movement of air|Bone production|Urine filtration only|Memory storage', 0, 'A narrowed airway can restrict airflow and impair breathing.'],
  ['Which finding can indicate increased work of breathing during an assessment?', 'Speaking only in short sentences|Warm hands|Normal relaxed speech|A healed bruise', 0, 'Speaking only in short sentences can indicate increased work of breathing.'],
  ['What is the relationship between breathing and metabolism?', 'Breathing supplies oxygen for cellular reactions|Breathing stops all metabolism|Metabolism produces no waste|They are unrelated', 0, 'Breathing supplies oxygen and removes carbon dioxide produced by metabolism.'],
  ['Why is a branching airway useful?', 'It distributes air throughout the lungs|It pumps blood|It stores urine|It supports the spinal cord', 0, 'Branching airways deliver air to a large area of lung tissue.'],
  ['What is the respiratory system connected to through gas transport?', 'Cardiovascular circulation|Only the skin|Only the reproductive tract|Only the bones', 0, 'Blood links pulmonary gas exchange with tissue oxygen delivery.'],
  ['What is the role of the nasopharynx in respiration?', 'It provides an upper airway route for air|It pumps blood|It makes ATP directly|It filters lymph', 0, 'The nasopharynx provides an upper airway route for air.'],
  ['What is a serious consequence of ineffective gas exchange?', 'Reduced oxygen delivery to tissues|Improved energy production|Increased bone growth|More urine storage', 0, 'Poor gas exchange can reduce oxygen delivery and impair cellular function.'],
  ['Which statement best summarises the respiratory system?', 'It moves air, exchanges gases and supports regulation|It only creates speech|It only filters blood|It only controls movement', 0, 'The respiratory system has several functions beyond ventilation, including gas exchange and acid-base regulation.']
]);

addQuestions('nervous', [
  ['What are the two main divisions of the nervous system?', 'Central and peripheral|Upper and lower|Cardiac and skeletal|Sensory and digestive', 0, 'The CNS is the brain and spinal cord; the PNS is the network of nerves outside them.'],
  ['What structures make up the central nervous system?', 'Brain and spinal cord|Heart and lungs|Nerves and muscles only|Brain and kidneys', 0, 'The CNS consists of the brain and spinal cord.'],
  ['What does the peripheral nervous system include?', 'Nerves outside the brain and spinal cord|Only the cerebrum|Only the spinal cord|The heart valves', 0, 'The PNS includes nerves outside the brain and spinal cord.'],
  ['What do sensory or afferent nerves carry?', 'Information towards the CNS|Instructions away from the CNS|Blood to the heart|Urine to the bladder', 0, 'Afferent nerves carry sensory information towards the brain and spinal cord.'],
  ['What do motor or efferent nerves carry?', 'Instructions from the CNS to the body|Oxygen to the lungs|Lymph to tissues|Food to the stomach', 0, 'Efferent nerves carry motor commands away from the CNS.'],
  ['What is the main functional cell of the nervous system?', 'Neuron|Red blood cell|Osteocyte|Platelet', 0, 'Neurons generate and conduct electrochemical impulses.'],
  ['Which part of a neuron receives input?', 'Dendrites|Axon|Meninges|Ventricle', 0, 'Dendrites receive signals and carry them towards the cell body.'],
  ['Which part transmits signals away from the cell body?', 'Axon|Dendrite|Nucleus only|CSF', 0, 'The axon transmits electrical signals towards its terminals.'],
  ['Where is the nucleus of a neuron found?', 'Cell body|Axon terminal only|Myelin sheath|Synaptic cleft', 0, 'The cell body contains the nucleus and other organelles.'],
  ['What is the role of myelin?', 'Help impulses travel faster|Make blood clot|Produce urine|Protect the heart valve', 0, 'Myelin sheaths support faster conduction of electrical impulses.'],
  ['What forms myelin in the peripheral nervous system?', 'Schwann cells|Red cells|Platelets|Alveoli', 0, 'The material identifies Schwann cells in relation to peripheral myelin.'],
  ['What are neuroglia?', 'Supporting cells of nervous tissue|Heart chambers|Lung sacs|Blood vessels', 0, 'Neuroglia support neurons and can help form a blood-brain barrier and clear debris.'],
  ['Which is a main nervous system function?', 'Controlling movement|Filtering inspired air|Producing bile|Making urine', 0, 'The nervous system controls body movement and coordinates responses.'],
  ['Which system division is voluntary?', 'Somatic nervous system|Parasympathetic only|Enteric only|Endocrine system', 0, 'The somatic system allows conscious control of skeletal muscle.'],
  ['What is a reflex primarily?', 'A protective involuntary response|A type of blood vessel|A digestive enzyme|A brain lobe', 0, 'Reflexes are involuntary and primarily protective.'],
  ['Which divisions are part of the autonomic nervous system?', 'Sympathetic, parasympathetic and enteric|Frontal, parietal and temporal|Cervical, thoracic and lumbar|Right, left and central', 0, 'The ANS has sympathetic, parasympathetic and enteric divisions.'],
  ['What does the sympathetic division prepare the body for?', 'Stress and strenuous activity|Sleep only|Digestion only|Bone repair only', 0, 'Sympathetic activity is associated with fight or flight and increased vigilance.'],
  ['What does sympathetic activity do to the airways?', 'Opens them|Closes them completely|Fills them with blood|Turns them into bone', 0, 'The sympathetic division opens the airways as part of the stress response.'],
  ['What is a general effect of the parasympathetic division?', 'Rest and digestion|Fight or flight|Voluntary skeletal movement only|Bone growth', 0, 'Parasympathetic activity supports rest, digestion and a peacemaker effect.'],
  ['What does the enteric division mainly regulate?', 'The gastrointestinal tract|The skull bones|The retina only|The heart valves only', 0, 'The enteric system contains neurons in the gut and modifies motility and secretions.'],
  ['Which four major sections of the brain are listed?', 'Brain stem, cerebellum, diencephalon and cerebrum|Kidney, liver, spleen and heart|Frontal, cervical, lumbar and sacral|Pons, skin, bladder and lung', 0, 'The supplied nervous system material divides the brain into these four sections.'],
  ['Which structures make up the brain stem?', 'Midbrain, pons and medulla oblongata|Frontal, parietal and temporal lobes|Dura, arachnoid and pia|Cervical, thoracic and lumbar areas', 0, 'The brain stem consists of the midbrain, pons and medulla oblongata.'],
  ['What does the medulla help manage?', 'Heart rate, blood pressure and breathing|Bone mineral storage|Urine colour|Skin sensation only', 0, 'The medulla contains centres involved in heart rate, BP and breathing.'],
  ['What is the cerebellum responsible for?', 'Coordination, posture and balance|Speech production only|Urine production|Gas exchange', 0, 'The cerebellum coordinates complex movement and regulates posture and balance.'],
  ['Where is the diencephalon located?', 'Deep beneath the cerebrum|Inside the spinal cord only|In the lungs|Below the bladder', 0, 'The diencephalon lies deep within the brain beneath the cerebrum.'],
  ['What does the thalamus do?', 'Relays sensory input to the cerebral cortex|Pumps blood|Produces urine|Controls the diaphragm directly', 0, 'The thalamus relays sensory input and contributes to perception.'],
  ['What does the hypothalamus help regulate?', 'Temperature, eating, drinking and autonomic activity|Bone length|Air filtration|Blood clotting only', 0, 'The hypothalamus integrates autonomic activity and regulates several homeostatic behaviours.'],
  ['How many major externally visible lobes are usually described in each cerebral hemisphere?', 'Four|Two|Three|Eight', 0, 'Each hemisphere is divided into frontal, parietal, temporal and occipital lobes.'],
  ['What are the three meninges?', 'Dura mater, arachnoid mater and pia mater|Pleura, pericardium and peritoneum|Cortex, medulla and pons|Axon, dendrite and soma', 0, 'The meninges are three protective layers around the brain and spinal cord.'],
  ['What does cerebrospinal fluid do?', 'Protects the CNS and carries nutrients|Pumps blood|Digests food|Moves skeletal muscles', 0, 'CSF protects the brain and spinal cord and carries oxygen, glucose and nutrients.']
]);

addQuestions('lymphatic-urinary-reproductive', [
  ['What is a key function of the lymphatic system?', 'Drain tissue fluid and support immunity|Pump blood|Exchange lung gases|Control voluntary movement', 0, 'The lymphatic system drains excess tissue fluid, filters it and helps fight infection.'],
  ['How does the lymphatic system work with the cardiovascular system?', 'It returns excess tissue fluid to the bloodstream|It replaces the heart|It carries air to the lungs|It makes bones move', 0, 'Lymphatic drainage returns excess fluid from tissues to the circulation.'],
  ['Where are lymphatic vessels found?', 'Throughout the body|Only in the skull|Only in the lungs|Only in the reproductive tract', 0, 'Lymph vessels are distributed throughout the body.'],
  ['What can lymphatic tissue help with?', 'Immune defence|Gas exchange|Voluntary movement|Speech production', 0, 'Lymphatic tissue and vessels support the immune system.'],
  ['What happens to excess tissue fluid?', 'It is drained by lymph vessels|It becomes bone|It is exhaled|It becomes a nerve impulse', 0, 'Lymph vessels drain excess fluid from tissues.'],
  ['What does lymph filtration support?', 'Removal of debris and immune monitoring|Heart contraction|Air filtration in the nose|Food digestion only', 0, 'Filtering lymph helps the body monitor and respond to infection.'],
  ['What is a broad function of the urinary system?', 'Waste removal and fluid balance|Memory formation|Air filtration|Speech production', 0, 'The urinary system removes metabolic waste and helps maintain fluid balance.'],
  ['What does the urinary system filter?', 'Blood|Inspired air|CSF only|Lymph only', 0, 'The kidneys filter the blood and form urine.'],
  ['What is removed in urine?', 'Metabolic waste|Oxygen for cells|Nerve impulses|Bone tissue', 0, 'Urine carries waste products out of the body.'],
  ['What balance does the urinary system help regulate?', 'Fluid and electrolytes|Sound and smell|Memory and speech|Joint movement', 0, 'Urinary function contributes to fluid and electrolyte balance.'],
  ['What does acid-base regulation help maintain?', 'A stable internal environment|A faster heartbeat only|Longer bones|More air filtration', 0, 'Removing acids and regulating body fluids supports homeostasis.'],
  ['What is the final storage site for urine?', 'Bladder|Ureter|Kidney cortex|Urethral sphincter only', 0, 'Urine is stored in the bladder before elimination.'],
  ['What carries urine from a kidney to the bladder?', 'Ureter|Urethra|Fallopian tube|Vena cava', 0, 'The ureters transport urine from the kidneys to the bladder.'],
  ['What carries urine from the bladder out of the body?', 'Urethra|Ureter|Aorta|Bronchus', 0, 'The urethra is the outlet from the bladder.'],
  ['What is one role of the kidneys?', 'Filter blood and regulate body fluids|Pump oxygenated blood|Make vocal sounds|Coordinate balance', 0, 'The kidneys filter blood and contribute to fluid and electrolyte regulation.'],
  ['What is a reproductive system function?', 'Support continuation of life|Filter inspired air|Drain all tissue fluid|Control pupil size only', 0, 'Reproductive systems produce gametes and support reproduction.'],
  ['Which reproductive cells are produced by the female reproductive system?', 'Ova|Spermatozoa|Urine|Cerebrospinal fluid', 0, 'The female reproductive system produces ova.'],
  ['What do the ovaries produce?', 'Ova and reproductive hormones|Urine|Bile|CSF', 0, 'Ovaries form ova and contribute to hormonal regulation.'],
  ['What is the role of the fallopian tubes?', 'Provide a route from ovary towards uterus|Store urine|Filter lymph|Produce CSF', 0, 'Fallopian tubes transport the ovum towards the uterus and are part of the reproductive tract.'],
  ['What is the uterus?', 'The organ that supports foetal development|A blood vessel|A lung passage|A lymph node', 0, 'The uterus supports implantation and foetal development.'],
  ['What is the cervix?', 'The neck of the uterus|The end of a ureter|A brain lobe|A heart valve', 0, 'The cervix is the lower neck of the uterus.'],
  ['What is lactation?', 'Production of breast milk|Formation of urine|Release of CSF|Gas exchange', 0, 'Lactation is the production of breast milk.'],
  ['What does the male reproductive system produce?', 'Spermatozoa|Ova|Urine only|Lymph', 0, 'The male reproductive system produces, matures and stores spermatozoa.'],
  ['Where do spermatozoa mature and become stored?', 'The epididymis|The lungs|The bladder|The cerebellum', 0, 'Sperm mature and are stored in the epididymis.'],
  ['What is semen?', 'Fluid carrying spermatozoa|Filtered lymph|Cerebrospinal fluid|Deoxygenated blood', 0, 'Semen carries spermatozoa for delivery into the female reproductive tract.'],
  ['What is the role of reproductive ducts?', 'Transport reproductive cells or secretions|Exchange oxygen|Filter blood|Control balance', 0, 'Ducts provide routes for reproductive cells and secretions.'],
  ['Which functions of the lymphatic and urinary systems support homeostasis?', 'Fluid balance, waste removal and immune support|Voluntary movement and speech|Gas exchange only|ATP production only', 0, 'The lymphatic and urinary systems support fluid balance, waste removal and immune function.'],
  ['What can impaired urinary function affect?', 'Waste removal and fluid balance|Only smell|Only speech|Only skeletal movement', 0, 'Urinary problems can affect the removal of waste and regulation of body fluids.'],
  ['What can impaired lymphatic drainage cause?', 'Accumulation of tissue fluid|Improved gas exchange|More ATP production|Faster nerve impulses', 0, 'If drainage is impaired, excess tissue fluid can accumulate.'],
  ['Which statement best describes the combined topic?', 'The systems support fluid balance, waste removal, immunity and reproduction|They are all parts of the brain|They only move blood|They only make vocal sounds', 0, 'The topic connects lymphatic, urinary and reproductive functions to body maintenance and reproduction.']
]);

addQuestions('body', [
  ['Which process uses oxygen to release energy from nutrients?', 'Cellular respiration|Osmosis|Filtration|Mitosis', 0, 'Cellular respiration uses oxygen and nutrients to produce usable energy in ATP.'],
  ['Which organ system provides the body’s external protective covering?', 'Integumentary|Urinary|Endocrine|Lymphatic', 0, 'The integumentary system includes skin, hair and nails and forms an external barrier.'],
  ['What is homeostasis?', 'Maintaining a stable internal environment|Increasing body size|Making only nerve cells|Stopping all change', 0, 'Homeostasis keeps internal conditions within suitable limits despite external change.'],
  ['Which body cavity contains the lungs?', 'Thoracic cavity|Cranial cavity|Pelvic cavity|Spinal cavity only', 0, 'The lungs lie in the thoracic cavity.'],
  ['Which cavity contains the brain?', 'Cranial cavity|Abdominal cavity|Pelvic cavity|Thoracic cavity', 0, 'The brain is protected within the cranial cavity.'],
  ['What is the anatomical position?', 'Standing upright with palms facing forward|Lying face down|Sitting with arms crossed|Standing with palms facing backwards', 0, 'Anatomical position is upright, facing forward, with arms at the sides and palms facing forward.'],
  ['What does anterior mean?', 'Towards the front|Towards the back|Further from the midline|Closer to the feet', 0, 'Anterior describes a position towards the front of the body.'],
  ['What does posterior mean?', 'Towards the back|Towards the front|Above the head|Near the midline only', 0, 'Posterior describes a position towards the back of the body.'],
  ['What does proximal mean?', 'Closer to the point of attachment|Further from the point of attachment|Near the skin surface|Below another structure', 0, 'Proximal means nearer to the point where a limb or structure attaches.'],
  ['What does distal mean?', 'Further from the point of attachment|Closer to the trunk|Inside a body cavity|Towards the midline', 0, 'Distal means further from the point of attachment.'],
  ['Which tissue stores energy and helps insulate the body?', 'Adipose connective tissue|Epithelial tissue|Nervous tissue|Cartilage only', 0, 'Adipose tissue stores fat and provides insulation and cushioning.'],
  ['What is a tissue?', 'A group of similar cells with a common function|A single atom|Several body systems|A chemical element only', 0, 'Tissues are groups of specialised cells working together.'],
  ['What is an organ?', 'A structure made from different tissues|A single molecule|A body cavity|A type of atom', 0, 'Organs contain multiple tissue types arranged to perform a function.'],
  ['Which process produces two genetically similar cells?', 'Mitosis|Diffusion|Filtration|Exocytosis', 0, 'Mitosis produces two genetically similar daughter cells for growth and repair.'],
  ['What is the role of enzymes?', 'Speed up chemical reactions|Store bones|Carry urine|Transmit sound only', 0, 'Enzymes are biological catalysts that speed up chemical reactions.'],
  ['Which movement requires cellular energy?', 'Active transport|Simple diffusion|Osmosis only|Passive filtration only', 0, 'Active transport moves substances against a concentration gradient using energy.'],
  ['What does a receptor detect?', 'A stimulus|A bone fracture only|A hormone gland only|A tissue layer', 0, 'Receptors detect changes in the internal or external environment.'],
  ['What is a stimulus?', 'A detectable change|A type of tissue|A body cavity|A stored nutrient only', 0, 'A stimulus is a change that can be detected and may trigger a response.'],
  ['Which system contributes to hormone control?', 'Endocrine|Skeletal only|Integumentary only|Respiratory only', 0, 'The endocrine system releases hormones that coordinate body functions.'],
  ['What stable condition do body systems help maintain?', 'The internal environment, or homeostasis|Complete absence of movement|Only bone formation|Elimination of communication', 0, 'Body systems are interdependent and cooperate to maintain the internal environment.']
]);

addQuestions('cardiovascular', [
  ['Which chamber receives blood from the superior and inferior venae cavae?', 'Right atrium|Right ventricle|Left atrium|Left ventricle', 0, 'The right atrium receives systemic venous blood from the superior and inferior venae cavae.'],
  ['Which chamber pumps blood to the lungs?', 'Right ventricle|Right atrium|Left atrium|Left ventricle', 0, 'The right ventricle pumps deoxygenated blood through the pulmonary valve to the lungs.'],
  ['Which chamber receives blood from the pulmonary veins?', 'Left atrium|Right atrium|Right ventricle|Left ventricle', 0, 'The left atrium receives oxygenated blood returning from the lungs.'],
  ['Which chamber pumps blood into the aorta?', 'Left ventricle|Left atrium|Right ventricle|Right atrium', 0, 'The left ventricle ejects oxygenated blood through the aortic valve into the aorta.'],
  ['What is the myocardium?', 'Heart muscle|Inner vessel lining|Blood plasma|A heart valve', 0, 'The myocardium is the muscular layer of the heart wall.'],
  ['What is the septum?', 'Wall separating the heart sides|A vessel leaving the heart|A coronary valve|A blood cell', 0, 'The septum separates the right and left sides of the heart.'],
  ['Which vessels carry blood away from the left ventricle into the systemic circulation?', 'Arteries|Veins|Capillaries only|Venules only', 0, 'Arteries carry blood away from the heart; the aorta carries blood from the left ventricle into the systemic circulation.'],
  ['Which vessels return blood towards the heart?', 'Veins|Arteries|Arterioles only|Capillaries only', 0, 'Veins return blood towards the heart.'],
  ['Where does most exchange with tissues occur?', 'Capillaries|Aorta|Vena cava|Pulmonary trunk', 0, 'Thin-walled capillaries allow exchange of gases, nutrients and waste with tissues.'],
  ['What is the function of valves in veins?', 'Limit backflow|Increase red cell production|Exchange gases|Create lymph', 0, 'Venous valves help keep low-pressure blood moving towards the heart.'],
  ['What does systole describe?', 'Contraction of the heart|Relaxation only|Blood clotting|Gas exchange', 0, 'Systole is the contraction phase of the cardiac cycle.'],
  ['What does diastole describe?', 'Relaxation and filling|Ventricular ejection only|Arterial narrowing|Clot formation', 0, 'Diastole is the relaxation and filling phase of the cardiac cycle.'],
  ['What initiates the normal heartbeat according to the material?', 'Electrical activity in cardiac tissue|The pulmonary valve|The vena cava|Skeletal muscle contraction', 0, 'Specialised cardiac cells generate and conduct electrical impulses that coordinate contraction.'],
  ['Which vessels branch from the aorta to supply the myocardium?', 'Coronary arteries|Pulmonary veins|Venae cavae|Renal veins', 0, 'Coronary arteries branch from the aorta and supply oxygenated blood to the myocardium.'],
  ['What does haemoglobin transport?', 'Oxygen|Urine|Bile|Cerebrospinal fluid', 0, 'Haemoglobin in red blood cells binds and transports oxygen.'],
  ['What is plasma?', 'The liquid part of blood|A heart chamber|A blood valve|A type of artery', 0, 'Plasma is the fluid medium carrying cells and dissolved substances.'],
  ['Which blood component helps clotting?', 'Platelets|Red blood cells|Plasma water only|Neurons', 0, 'Platelets help form clots and limit blood loss after vessel injury.'],
  ['What is pulse?', 'The pressure wave from ventricular contraction|The sound of breathing|A lymph flow|A nerve cell', 0, 'A pulse is the palpable arterial pressure wave produced by heart contraction.'],
  ['What is blood pressure?', 'Force exerted by blood on vessel walls|The amount of oxygen in a cell|The speed of a nerve impulse|The volume of urine', 0, 'Blood pressure is the force blood exerts against vessel walls.'],
  ['Why is the left ventricle thicker than the right?', 'It pumps around the systemic circuit|It receives blood from the vena cava|It stores platelets|It pumps only to the atrium', 0, 'The left ventricle needs greater pressure to drive blood through the whole body.']
]);

addQuestions('respiratory', [
  ['What is ventilation?', 'Movement of air into and out of the lungs|Movement of blood through veins|Diffusion of glucose|Production of urine', 0, 'Ventilation is breathing: moving air into and out of the lungs.'],
  ['What is external respiration?', 'Gas exchange between alveoli and blood|Gas exchange between blood and cells|Cellular ATP production|Movement of food', 0, 'External respiration is exchange between alveolar air and pulmonary capillary blood.'],
  ['What is internal respiration?', 'Gas exchange between blood and body tissues|Air movement through the nose|Swallowing|Sound production', 0, 'Internal respiration is exchange between systemic blood and body cells.'],
  ['Which gas moves from alveoli into pulmonary blood?', 'Oxygen|Carbon dioxide only|Nitrogen only|Water vapour only', 0, 'Oxygen diffuses from alveolar air into the blood.'],
  ['Which gas moves from pulmonary blood into alveoli?', 'Carbon dioxide|Oxygen only|Glucose|Nitrogen only', 0, 'Carbon dioxide diffuses from blood into alveoli for expiration.'],
  ['What is the function of mucus in the airway?', 'Trap particles|Pump blood|Digest protein|Make red cells', 0, 'Mucus traps dust and microorganisms so they can be removed.'],
  ['What do cilia do in the airway?', 'Move mucus towards the pharynx|Exchange oxygen directly|Close the epiglottis|Contract the diaphragm', 0, 'Cilia move mucus and trapped material towards the pharynx for removal or swallowing.'],
  ['What is the carina?', 'The point where the trachea divides|The top of the larynx|A lung membrane|An alveolar cell', 0, 'The carina is where the trachea divides into the main bronchi.'],
  ['Why is an inhaled object more likely to enter the right bronchus?', 'It is shorter, wider and more vertical|It has no cartilage|It leads directly to the stomach|It is narrower and horizontal', 0, 'The right main bronchus is shorter, wider and more vertical.'],
  ['What are bronchioles?', 'Smaller branches of the bronchi|Blood vessels in the heart|Muscles between ribs|Lung membranes', 0, 'Bronchi divide into progressively smaller bronchioles leading towards alveoli.'],
  ['What is surfactant?', 'A substance reducing alveolar surface tension|A blood clotting factor|A nasal bone|A digestive enzyme', 0, 'Surfactant reduces surface tension and helps prevent alveoli collapsing.'],
  ['What is the pleura?', 'A double membrane around each lung|A throat muscle|A blood cell|A kidney structure', 0, 'The pleura surrounds each lung and helps it move smoothly during breathing.'],
  ['What is the pleural cavity filled with?', 'A thin film of lubricating fluid|Air at high pressure|Urine|Digestive acid', 0, 'Pleural fluid reduces friction between the pleural layers.'],
  ['Which muscle is the main muscle of inspiration?', 'Diaphragm|Biceps|Cardiac muscle|Pelvic floor only', 0, 'Contraction of the diaphragm increases thoracic volume and draws air into the lungs.'],
  ['What happens to thoracic volume during inspiration?', 'It increases|It becomes zero|It decreases immediately|It stays fixed', 0, 'Thoracic expansion lowers pressure and allows air to enter the lungs.'],
  ['What happens to intrapulmonary pressure during inspiration?', 'It falls below atmospheric pressure|It rises above all pressure|It becomes zero|It equals blood pressure', 0, 'Air flows in when pressure inside the lungs falls below atmospheric pressure.'],
  ['What is tidal volume?', 'The air moved in a normal breath|Maximum exhaled air|Air left after forced exhalation|The total lung capacity only', 0, 'Tidal volume is the volume of air moved during a normal quiet breath.'],
  ['Where are the vocal cords?', 'In the larynx|In the alveoli|In the bronchioles|In the diaphragm', 0, 'The vocal cords are in the larynx and vibrate to produce sound.'],
  ['How does the respiratory system help acid-base balance?', 'By removing carbon dioxide|By producing urea|By storing calcium|By making lymph', 0, 'Removing carbon dioxide affects carbonic acid levels and therefore blood pH.'],
  ['What makes diffusion efficient at the alveoli?', 'Thin walls, large surface area and good blood supply|Thick cartilage rings|No capillaries|A dry lining', 0, 'Alveoli provide a large, thin, moist exchange surface closely surrounded by capillaries.']
]);

addQuestions('nervous', [
  ['What is the main function of dendrites?', 'Receive incoming information|Carry urine|Contract the heart|Produce myelin only', 0, 'Dendrites receive signals towards the neuron cell body.'],
  ['What is the main function of an axon?', 'Conduct impulses away from the cell body|Filter blood|Store lymph|Make red blood cells', 0, 'An axon conducts the nerve impulse away from the cell body.'],
  ['What is the role of the cell body?', 'Contains the nucleus and organelles|Forms the vertebral column|Exchanges gases|Stores urine', 0, 'The cell body contains the nucleus and organelles needed to maintain the neuron.'],
  ['What is a synapse?', 'A junction for communication between cells|A brain lobe|A spinal bone|A blood vessel', 0, 'A synapse is the junction where a neuron communicates with another cell.'],
  ['What is the role of Schwann cells?', 'Produce myelin around peripheral axons|Pump cerebrospinal fluid|Make hormones|Form the skull', 0, 'Schwann cells form myelin sheaths around peripheral nerve fibres.'],
  ['What is the function of nodes of Ranvier?', 'Allow rapid impulse transmission along myelinated axons|Store neurotransmitters in blood|Protect the brain from impact|Detect odours', 0, 'Nodes allow impulses to jump between gaps in the myelin sheath.'],
  ['Which structure coordinates posture and balance?', 'Cerebellum|Medulla|Thalamus|Frontal lobe only', 0, 'The cerebellum coordinates skilled movement, posture and balance.'],
  ['Which brain region helps regulate temperature and eating?', 'Hypothalamus|Occipital lobe|Pons only|Spinal nerve', 0, 'The hypothalamus regulates temperature, eating, drinking and other homeostatic functions.'],
  ['Which brain structure relays sensory information to the cortex?', 'Thalamus|Cerebellum|Pia mater|Cauda equina', 0, 'The thalamus is a major relay for sensory information.'],
  ['Which lobe is most associated with vision?', 'Occipital|Frontal|Parietal|Temporal', 0, 'The occipital lobe processes visual information.'],
  ['Which lobe is associated with hearing and memory?', 'Temporal|Occipital|Frontal|Parietal', 0, 'The temporal lobe supports hearing, memory and aspects of language.'],
  ['Which lobe contributes to planning and voluntary movement?', 'Frontal|Temporal|Occipital|Cerebellar only', 0, 'The frontal lobe supports planning, behaviour, speech and voluntary motor control.'],
  ['Which lobe processes body sensation?', 'Parietal|Occipital|Temporal|Medullary', 0, 'The parietal lobe processes somatic sensation and spatial information.'],
  ['What is the outer meningeal layer?', 'Dura mater|Arachnoid mater|Pia mater|Endocardium', 0, 'The dura mater is the tough outer meningeal layer.'],
  ['Where is cerebrospinal fluid found around the meninges?', 'Subarachnoid space|Inside the dura only|Inside a tendon|In the myocardium', 0, 'CSF circulates in the subarachnoid space around the brain and spinal cord.'],
  ['What is one function of CSF?', 'Protect the brain and spinal cord|Contract skeletal muscle|Digest fat|Carry urine', 0, 'CSF provides physical and chemical protection and helps transport nutrients and waste.'],
  ['Which structure connects the brain with spinal nerves?', 'Spinal cord|Thalamus only|Cerebral cortex only|Lateral sulcus', 0, 'The spinal cord carries sensory and motor pathways between the brain and spinal nerves.'],
  ['How many pairs of spinal nerves are there?', '31|12|24|33', 0, 'There are 31 pairs of spinal nerves.'],
  ['What does the sympathetic division generally do?', 'Prepares the body for stress|Stimulates rest and digestion|Makes CSF|Controls vision only', 0, 'Sympathetic activity supports the fight-or-flight response.'],
  ['What does the parasympathetic division generally do?', 'Supports rest and digestion|Opens airways for maximum activity|Raises cardiac activity for stress|Stops all gut activity', 0, 'Parasympathetic activity supports recovery, digestion and energy conservation.']
]);

addQuestions('lymphatic-urinary-reproductive', [
  ['What does the lymphatic system return to the bloodstream?', 'Excess tissue fluid as lymph|Air from the lungs|Urine from the bladder|Bile from the liver', 0, 'Lymphatic vessels collect excess tissue fluid and return it to the venous circulation as lymph.'],
  ['What is filtered in a lymph node?', 'Lymph|Urine|Air|Cerebrospinal fluid', 0, 'Lymph nodes filter lymph and expose its contents to immune cells.'],
  ['Which cells recognise foreign antigens?', 'Lymphocytes|Red blood cells|Platelets|Osteocytes', 0, 'Lymphocytes recognise antigens and coordinate specific immune responses.'],
  ['Which organ filters blood and removes old red blood cells?', 'Spleen|Thymus|Bladder|Pancreas', 0, 'The spleen filters blood and removes old or damaged red blood cells.'],
  ['Where do T lymphocytes mature?', 'Thymus|Spleen|Kidney cortex|Ovary', 0, 'T lymphocytes mature in the thymus.'],
  ['What do lacteals absorb?', 'Dietary fats|Urine|Oxygen|Red blood cells', 0, 'Lacteals absorb dietary fats from the small intestine into lymph.'],
  ['What is the functional unit of the kidney?', 'Nephron|Alveolus|Neuron|Lymph node', 0, 'The nephron filters blood and forms urine.'],
  ['What is the glomerulus?', 'A capillary network for filtration|A bladder muscle|A reproductive duct|A lymphatic valve', 0, 'The glomerulus is a capillary network where filtration begins.'],
  ['What is Bowman capsule?', 'The cup surrounding the glomerulus|The outer kidney capsule only|A ureter valve|A testicular duct', 0, 'Bowman capsule collects fluid filtered from glomerular capillaries.'],
  ['Which useful substances may be selectively reabsorbed from renal filtrate?', 'Glucose and water|All red blood cells|All bacteria|Only air', 0, 'Selective reabsorption returns useful water, glucose, amino acids and ions to the blood.'],
  ['Which substances may be secreted from the blood into the nephron?', 'Hydrogen ions and some drugs|Oxygen into alveoli|Sperm into the uterus|Lymph into nodes', 0, 'Tubular secretion moves selected waste substances from blood into the nephron.'],
  ['What is the function of antidiuretic hormone?', 'Increase water reabsorption|Prevent all filtration|Make sperm|Digest fats', 0, 'Antidiuretic hormone increases water reabsorption in the collecting ducts.'],
  ['Which tube carries urine from kidney to bladder?', 'Ureter|Urethra|Vas deferens|Fallopian tube', 0, 'The ureter transports urine from the renal pelvis to the bladder.'],
  ['What does the bladder do?', 'Stores urine|Filters blood|Produces ova|Matures T cells', 0, 'The bladder stores urine before micturition.'],
  ['Which muscle contracts to empty the bladder?', 'Detrusor muscle|Diaphragm|Myocardium|Biceps', 0, 'The detrusor muscle contracts during micturition.'],
  ['What do the testes produce?', 'Spermatozoa and testosterone|Ova and progesterone|Urine and urea|Lymph and antibodies only', 0, 'The testes produce male gametes and testosterone.'],
  ['Where do sperm mature?', 'Epididymis|Ureter|Cervix|Renal pelvis', 0, 'Sperm mature and are stored in the epididymis.'],
  ['Which gland contributes fluid to semen?', 'Prostate gland|Thyroid gland|Adrenal cortex|Pituitary only', 0, 'The prostate is an accessory gland that contributes fluid to semen.'],
  ['Which female organs release ova and produce reproductive hormones?', 'Ovaries|Uterine tubes|Cervix|Vagina', 0, 'The ovaries release ova and produce oestrogen and progesterone.'],
  ['Where does fertilisation usually occur?', 'Uterine tube|Uterus only|Cervix|Vagina', 0, 'Fertilisation usually occurs in the uterine, or fallopian, tube.']
]);

addQuestions('body', [
  ['The smallest unit of life capable of replication is the _____.', 'cell|organ|tissue|system', 0, 'Cells are the smallest units of life capable of replication.'],
  ['A group of similar cells working together forms a _____.', 'tissue|molecule|cavity|system', 0, 'Similar specialised cells combine to form tissues.'],
  ['Different tissues arranged together form an _____.', 'organ|atom|electrolyte|element', 0, 'Organs are structures made from different tissues.'],
  ['Organs working together form a body _____.', 'system|cell|molecule|membrane', 0, 'Organs cooperate as body systems.'],
  ['The study of body structure is called _____.', 'anatomy|physiology|metabolism|pathology', 0, 'Anatomy studies body structure.'],
  ['The study of how the body works is called _____.', 'physiology|anatomy|histology|chemistry', 0, 'Physiology explains how the body and its systems function.'],
  ['The study of abnormal changes caused by illness or injury is _____.', 'pathophysiology|anatomy|homeostasis|diffusion', 0, 'Pathophysiology considers the effects of disease and injury.'],
  ['The nucleus contains the cell genetic material called _____.', 'DNA|ATP|bile|plasma', 0, 'DNA contains genetic instructions in the nucleus.'],
  ['The cell membrane controls what enters and leaves the _____.', 'cell|bone|organ system|blood vessel', 0, 'The cell membrane is a selective barrier.'],
  ['Most cellular ATP is produced by the _____.', 'mitochondrion|nucleus|lysosome|ribosome', 0, 'Mitochondria produce most usable cellular ATP.'],
  ['Lysosomes break down and _____ used cell components.', 'recycle|oxygenate|contract|filter', 0, 'Lysosomes digest and recycle cellular material.'],
  ['ATP is often described as the body’s usable energy _____.', 'store|barrier|receptor|hormone', 0, 'ATP provides immediately usable cellular energy.'],
  ['The sum of chemical reactions in cells is called _____.', 'metabolism|osmosis|anatomy|ventilation', 0, 'Metabolism is the total of cellular chemical reactions.'],
  ['Diffusion moves particles from a _____ concentration to a lower concentration.', 'high|low|neutral|fixed', 0, 'Diffusion follows a concentration gradient from high to low.'],
  ['Osmosis is the movement of _____ across a semi-permeable membrane.', 'water|bone|ATP|protein only', 0, 'Osmosis describes water movement across a semi-permeable membrane.'],
  ['Active transport requires cellular _____.', 'energy|silence|light|cartilage', 0, 'Active transport uses energy to move substances against a gradient.'],
  ['Epithelial tissue covers surfaces and _____ organs.', 'lines|pumps|contracts|filters only', 0, 'Epithelial tissue covers the outside and lines internal surfaces.'],
  ['Bone, cartilage, blood and adipose are examples of _____ tissue.', 'connective|epithelial|nervous|cardiac', 0, 'These are all connective tissue types.'],
  ['Muscle tissue contracts to produce _____.', 'movement|DNA|urine|CSF', 0, 'Muscle contraction produces movement.'],
  ['Nervous tissue detects information and carries electrical _____.', 'impulses|enzymes|nutrients|electrolytes only', 0, 'Nervous tissue generates and conducts electrical impulses.'],
  ['Homeostasis maintains a stable _____ environment.', 'internal|external|skeletal|respiratory only', 0, 'Homeostasis keeps internal conditions within suitable limits.'],
  ['The cardiovascular system transports oxygen and _____.', 'nutrients|urine|CSF|spermatozoa', 0, 'Blood transports oxygen, nutrients and other substances.'],
  ['The respiratory system exchanges oxygen and _____.', 'carbon dioxide|urea|bile|lymph', 0, 'Respiration brings in oxygen and removes carbon dioxide.'],
  ['The urinary system removes metabolic waste in _____.', 'urine|lymph|semen|CSF', 0, 'Urine carries metabolic waste out of the body.'],
  ['The body systems work together to maintain _____.', 'life and homeostasis|bone length only|one temperature only|cell colour', 0, 'Interdependent systems support life and internal balance.']
]);

addQuestions('cardiovascular', [
  ['The right atrium receives blood from the superior and inferior _____.', 'venae cavae|pulmonary veins|coronary arteries|aorta', 0, 'The venae cavae return systemic blood to the right atrium.'],
  ['The right ventricle pumps blood through the pulmonary valve into the pulmonary _____.', 'trunk|vein|aorta|sinus', 0, 'The pulmonary trunk carries blood from the right ventricle to the lungs.'],
  ['The left atrium receives oxygenated blood from the pulmonary _____.', 'veins|arteries|trunk|valves', 0, 'Pulmonary veins return oxygenated blood to the left atrium.'],
  ['The left ventricle ejects blood through the aortic valve into the _____.', 'aorta|vena cava|pulmonary vein|coronary sinus', 0, 'The aorta distributes blood from the left ventricle to the body.'],
  ['The valve between the right atrium and right ventricle is the _____ valve.', 'tricuspid|mitral|aortic|pulmonary', 0, 'The tricuspid valve lies between the right atrium and ventricle.'],
  ['The valve between the left atrium and left ventricle is the _____ valve.', 'mitral|tricuspid|pulmonary|aortic', 0, 'The mitral valve lies between the left atrium and ventricle.'],
  ['The heart muscle is called the _____.', 'myocardium|endocardium|pericardial fluid|septum', 0, 'The myocardium is the muscular heart layer.'],
  ['The wall separating the two sides of the heart is the _____.', 'septum|aorta|pericardium|coronary artery', 0, 'The septum separates the right and left sides.'],
  ['Pulmonary circulation carries blood between the heart and the _____.', 'lungs|kidneys|brain|liver only', 0, 'Pulmonary circulation connects the right heart to the lungs and back.'],
  ['Systemic circulation carries blood between the heart and the body’s _____.', 'tissues|alveoli only|bladder|lymph nodes only', 0, 'Systemic circulation supplies the body tissues.'],
  ['Arteries carry blood _____ from the heart.', 'away|towards|only around|through the valves', 0, 'Arteries carry blood away from the heart.'],
  ['Veins carry blood _____ the heart.', 'towards|away from|only into arteries|through alveoli', 0, 'Veins return blood towards the heart.'],
  ['The smallest vessels where exchange occurs are the _____.', 'capillaries|arteries|veins|venae cavae', 0, 'Capillaries have thin walls for exchange with tissues.'],
  ['Small vessels that branch from arteries are called _____.', 'arterioles|venules|veins|sinuses', 0, 'Arteries branch into arterioles before capillary beds.'],
  ['Small vessels that collect blood from capillaries are _____.', 'venules|arterioles|aorta|arteries', 0, 'Venules collect blood leaving capillary beds.'],
  ['The heart receives its own blood supply through the _____ arteries.', 'coronary|pulmonary|carotid|renal', 0, 'Coronary arteries supply the myocardium.'],
  ['The liquid part of blood is called _____.', 'plasma|serum only|haemoglobin|lymphocyte', 0, 'Plasma is the liquid medium carrying blood cells and dissolved substances.'],
  ['Red blood cells transport oxygen using _____.', 'haemoglobin|platelets|plasma proteins only|lymph', 0, 'Haemoglobin binds oxygen in red blood cells.'],
  ['Platelets help blood to _____.', 'clot|breathe|digest|filter', 0, 'Platelets contribute to clot formation.'],
  ['Heart relaxation and filling is called _____.', 'diastole|systole|perfusion|diffusion', 0, 'Diastole is the relaxation and filling phase.'],
  ['Heart contraction and ejection is called _____.', 'systole|diastole|osmosis|filtration', 0, 'Systole is the contraction phase.'],
  ['The palpable pressure wave produced by heart contraction is the _____.', 'pulse|murmur|valve|septum', 0, 'A pulse is the arterial pressure wave from ventricular contraction.'],
  ['The force of blood against vessel walls is called blood _____.', 'pressure|volume|flow|clotting', 0, 'Blood pressure is the force exerted on vessel walls.'],
  ['The cardiovascular system helps distribute _____ around the body.', 'heat|urine|CSF|lymph nodes', 0, 'Circulation distributes heat and contributes to temperature regulation.']
]);

addQuestions('respiratory', [
  ['Movement of air into and out of the lungs is called _____.', 'ventilation|filtration|perfusion|digestion', 0, 'Ventilation is the movement of air during breathing.'],
  ['The respiratory system transfers _____ from the atmosphere to the blood.', 'oxygen|urea|glucose|bile', 0, 'Oxygen diffuses from alveoli into pulmonary blood.'],
  ['The respiratory system removes _____ from the blood.', 'carbon dioxide|nitrogen|glucose|sodium', 0, 'Carbon dioxide diffuses into alveoli and is exhaled.'],
  ['The nose warms, moistens and _____ inspired air.', 'filters|pumps|digests|clots', 0, 'The nose filters particles while warming and humidifying air.'],
  ['The pharynx is shared by the respiratory and _____ systems.', 'digestive|urinary|lymphatic|reproductive', 0, 'The pharynx conducts both air and swallowed food.'],
  ['The pharynx is divided into the nasopharynx, oropharynx and _____.', 'hypopharynx|bronchiole|alveolus|pleura', 0, 'These are the three regions described in the material.'],
  ['The epiglottis helps prevent _____ during swallowing.', 'aspiration|ventilation|diffusion|perfusion', 0, 'The epiglottis closes the larynx to protect the lower airway.'],
  ['The larynx is also known as the _____ box.', 'voice|air|lung|sound', 0, 'The larynx is the voice box.'],
  ['The trachea is supported by incomplete _____ rings.', 'C-shaped cartilage|bone|muscle|elastic blood', 0, 'C-shaped cartilage rings help keep the trachea open.'],
  ['The trachea divides at the carina into the two main _____.', 'bronchi|alveoli|pleurae|lobes', 0, 'The main bronchi begin at the carina.'],
  ['The right main bronchus is shorter, wider and more _____.', 'vertical|horizontal|curved backwards|closed', 0, 'Its more vertical course makes it a common route for inhaled objects.'],
  ['Bronchi subdivide into smaller _____.', 'bronchioles|arterioles|venules|sinuses', 0, 'Bronchioles are the smaller airway branches.'],
  ['Bronchioles terminate at the _____.', 'alveoli|larynx|pharynx|tracheal rings', 0, 'Alveoli are the terminal gas-exchange sacs.'],
  ['Alveolar walls are approximately _____ cell thick.', 'one|two hundred|ten|zero', 0, 'Very thin alveolar walls shorten the diffusion distance.'],
  ['The large combined surface area of the alveoli helps make gas _____ efficient.', 'exchange|digestion|filtration|clotting', 0, 'Large surface area supports efficient oxygen and carbon dioxide exchange.'],
  ['Surfactant reduces alveolar surface _____.', 'tension|pressure only|temperature|volume', 0, 'Surfactant helps prevent alveolar collapse by reducing surface tension.'],
  ['The membrane surrounding each lung is the _____.', 'pleura|peritoneum|meninges|pericardium', 0, 'The pleura surrounds the lungs.'],
  ['The main muscle of inspiration is the _____.', 'diaphragm|myocardium|biceps|intercostal bone', 0, 'Diaphragm contraction expands the thoracic cavity.'],
  ['During inspiration, thoracic volume _____.', 'increases|decreases to zero|stays fixed|becomes negative', 0, 'Increasing thoracic volume lowers lung pressure and draws air in.'],
  ['During inspiration, pressure inside the lungs falls _____ atmospheric pressure.', 'below|above|equal to all|behind', 0, 'Air flows into the lungs when intrapulmonary pressure falls below atmospheric pressure.'],
  ['Air moved during a normal quiet breath is called _____ volume.', 'tidal|residual|vital|reserve', 0, 'Tidal volume is the air moved in a normal breath.'],
  ['The vocal cords are located in the _____.', 'larynx|trachea|alveoli|diaphragm', 0, 'The vocal cords in the larynx produce sound.'],
  ['Removing carbon dioxide helps regulate blood _____ balance.', 'acid-base|bone|fluid only|electrolyte only', 0, 'Carbon dioxide removal influences carbonic acid and blood pH.'],
  ['Expired air contains more carbon dioxide than _____ air.', 'inspired|filtered|humidified|alveolar only', 0, 'Body metabolism adds carbon dioxide to air before it is expired.'],
  ['The respiratory system contributes to the sense of _____.', 'smell|balance only|touch|pain only', 0, 'The material identifies smell as an additional respiratory function.']
]);

addQuestions('nervous', [
  ['The brain and spinal cord together form the _____ nervous system.', 'central|peripheral|somatic|enteric', 0, 'The CNS consists of the brain and spinal cord.'],
  ['The network of nerves outside the CNS is the _____ nervous system.', 'peripheral|central|cerebral|meningeal', 0, 'The PNS includes peripheral nerves and ganglia.'],
  ['Sensory nerves carrying information towards the CNS are called _____.', 'afferent|efferent|autonomic|motor only', 0, 'Afferent pathways carry sensory information towards the CNS.'],
  ['Motor nerves carrying instructions away from the CNS are called _____.', 'efferent|afferent|sensory|receptor', 0, 'Efferent pathways carry motor instructions away from the CNS.'],
  ['The branching parts of a neuron that receive input are _____.', 'dendrites|axons|synapses|myelin', 0, 'Dendrites receive incoming information.'],
  ['The part of a neuron that conducts signals away from the cell body is the _____.', 'axon|dendrite|nucleus|synaptic cleft', 0, 'The axon transmits the impulse away from the cell body.'],
  ['The neuron cell body contains the nucleus and other _____.', 'organelles|alveoli|valves|vertebrae', 0, 'Organelles in the cell body maintain neuronal function.'],
  ['The ends of axons that communicate chemically are called synaptic _____.', 'bulbs|nodes|lobes|ducts', 0, 'Synaptic bulbs release chemical signals at the end of an axon.'],
  ['The insulating covering around some axons is the _____ sheath.', 'myelin|meningeal|pleural|epithelial', 0, 'Myelin protects axons and speeds impulse transmission.'],
  ['In the peripheral nervous system, myelin is made by _____ cells.', 'Schwann|red blood|platelet|glial bone', 0, 'Schwann cells produce peripheral myelin.'],
  ['Gaps in the myelin sheath are called nodes of _____.', 'Ranvier|Cajal|Willis|Langerhans', 0, 'Nodes of Ranvier allow rapid transmission along myelinated axons.'],
  ['Support cells in nervous tissue are called _____.', 'neuroglia|nephrons|lymphocytes|osteocytes', 0, 'Neuroglia support and protect neurons.'],
  ['The medulla helps regulate heart rate, blood pressure and _____.', 'breathing|digestion only|vision|hearing', 0, 'The medulla contains important automatic control centres.'],
  ['The pons helps regulate _____ and relays information between brain regions.', 'breathing|urine production|blood clotting|menstruation', 0, 'The pons contributes to breathing regulation and relays information.'],
  ['The midbrain helps coordinate _____.', 'movement|urine storage|gas exchange|lymph drainage', 0, 'The midbrain contributes to movement coordination.'],
  ['The cerebellum coordinates skilled movement, posture and _____.', 'balance|speech production only|blood filtration|temperature only', 0, 'Balance is a key cerebellar function.'],
  ['The thalamus acts as a major sensory _____.', 'relay|muscle|ventricle|membrane', 0, 'The thalamus relays sensory information to the cortex.'],
  ['The hypothalamus helps regulate body _____ and eating and drinking.', 'temperature|bone density|haemoglobin|lung volume only', 0, 'Temperature, eating and drinking are hypothalamic functions.'],
  ['The outer grey layer of the cerebrum is the cerebral _____.', 'cortex|medulla|duct|capsule', 0, 'The cerebral cortex is the outer grey matter layer.'],
  ['The lobe involved in vision is the _____ lobe.', 'occipital|frontal|parietal|temporal', 0, 'The occipital lobe processes visual information.'],
  ['The lobe associated with hearing and memory is the _____ lobe.', 'temporal|occipital|frontal|parietal', 0, 'The temporal lobe supports hearing and memory.'],
  ['The tough outer meningeal layer is the _____ mater.', 'dura|pia|arachnoid|synovial', 0, 'Dura mater is the outer protective meningeal layer.'],
  ['Cerebrospinal fluid is found in the _____ space around the arachnoid mater.', 'subarachnoid|subdural only|pleural|peritoneal', 0, 'CSF circulates in the subarachnoid space.'],
  ['The spinal cord narrows at its lower end to form the _____ medullaris.', 'conus|cauda|corpus|central', 0, 'The conus medullaris is the tapered lower end of the spinal cord.']
]);

addQuestions('lymphatic-urinary-reproductive', [
  ['Excess tissue fluid entering lymphatic vessels becomes _____.', 'lymph|plasma|urine|semen', 0, 'Excess tissue fluid collected by lymphatics is called lymph.'],
  ['Lymphatic vessels eventually return lymph to the _____ circulation.', 'venous|arterial|pulmonary only|coronary only', 0, 'Lymph returns to large veins near the base of the neck.'],
  ['Lymph nodes filter _____.', 'lymph|urine|blood only|CSF', 0, 'Lymph nodes filter lymph and expose its contents to immune cells.'],
  ['Immune cells that recognise foreign antigens include _____.', 'lymphocytes|erythrocytes|platelets|osteocytes', 0, 'Lymphocytes recognise antigens and coordinate specific immune responses.'],
  ['The spleen filters _____ rather than lymph.', 'blood|urine|CSF|semen', 0, 'The spleen filters blood and removes old red blood cells.'],
  ['T lymphocytes mature in the _____.', 'thymus|spleen|kidney|pancreas', 0, 'The thymus is the site of T-cell maturation.'],
  ['Intestinal lymphatic capillaries that absorb fats are called _____.', 'lacteals|nephrons|alveoli|villi only', 0, 'Lacteals absorb dietary fats into the lymphatic system.'],
  ['Urine is stored in the _____ before elimination.', 'bladder|ureter|kidney cortex|renal artery', 0, 'The bladder stores urine before it is eliminated through the urethra.'],
  ['The functional unit of the kidney is the _____.', 'nephron|neuron|alveolus|lymph node', 0, 'Each nephron filters blood and helps form urine.'],
  ['The capillary network where kidney filtration begins is the _____.', 'glomerulus|collecting duct|renal pelvis|ureter', 0, 'The glomerulus filters fluid from the blood.'],
  ['The glomerulus is surrounded by Bowman’s _____.', 'capsule|duct|medulla|sphincter', 0, 'Bowman capsule collects the initial filtrate.'],
  ['Useful substances are returned to blood by selective _____.', 'reabsorption|aspiration|ventilation|ejaculation', 0, 'Reabsorption returns water, glucose, amino acids and ions to blood.'],
  ['Movement of substances from blood into the nephron is tubular _____.', 'secretion|filtration only|absorption|fertilisation', 0, 'Tubular secretion adds selected wastes to the filtrate.'],
  ['Antidiuretic hormone increases kidney _____ reabsorption.', 'water|protein|red cell|fat', 0, 'ADH increases water reabsorption in collecting ducts.'],
  ['The tube carrying urine from a kidney to the bladder is the _____.', 'ureter|urethra|vas deferens|fallopian tube', 0, 'The ureter transports urine to the bladder.'],
  ['The bladder stores _____ before it is eliminated.', 'urine|lymph|ova|sperm', 0, 'The bladder is a muscular urine reservoir.'],
  ['The muscular bladder wall that contracts during micturition is the _____ muscle.', 'detrusor|diaphragm|myocardial|sphincter only', 0, 'The detrusor contracts to empty the bladder.'],
  ['The testes produce spermatozoa and the hormone _____.', 'testosterone|oestrogen|progesterone|ADH', 0, 'Testosterone is produced by the testes.'],
  ['Sperm mature and are stored in the _____.', 'epididymis|ureter|prostate|cervix', 0, 'The epididymis is the site of sperm maturation and storage.'],
  ['The prostate is an accessory gland contributing fluid to _____.', 'semen|urine|lymph|CSF', 0, 'Prostatic fluid contributes to semen.'],
  ['The ovaries produce ova and the hormones oestrogen and _____.', 'progesterone|testosterone|ADH|insulin only', 0, 'The ovaries produce progesterone as well as oestrogen.'],
  ['The uterine tubes are the usual site of _____.', 'fertilisation|implantation only|urine formation|sperm maturation', 0, 'Fertilisation usually occurs in a uterine or fallopian tube.'],
  ['The uterus supports implantation and _____ development.', 'foetal|neural only|renal only|lymphatic', 0, 'The uterus supports development of the foetus during pregnancy.'],
  ['After birth, prolactin supports the production of breast _____.', 'milk|lymph|urine|semen', 0, 'Prolactin supports milk production during lactation.']
]);

addQuestions('cardiovascular', [
  ['The pulmonary valve lies between the right ventricle and the pulmonary _____.', 'trunk|vein|aorta|atrium', 0, 'The pulmonary valve controls blood leaving the right ventricle for the pulmonary trunk.']
]);

addQuestions('nervous', [
  ['The spinal cord carries afferent sensory and _____ motor information.', 'efferent|digestive|lymphatic|endocrine', 0, 'Afferent pathways carry sensory information in and efferent pathways carry motor instructions out.']
]);

addQuestions('lymphatic-urinary-reproductive', [
  ['The two main lymphatic ducts return lymph to large _____ near the base of the neck.', 'veins|arteries|bronchi|ureters', 0, 'The lymphatic ducts empty into large veins near the junction of the internal jugular and subclavian veins.']
]);

window.diagramQuestionDatabase = [
  { id: 'diagram-body-01', topic: 'body', type: 'diagram', question: 'Drag each level of organisation onto the matching part of the diagram.', explanation: 'The sequence is atom, molecule, cell, tissue, organ, organ system and organism.', diagram: { image: 'assets/test-diagrams/body-organisation-test.jpeg', alt: 'Body organisation diagram for the test', labels: [{ id: 'atom', name: 'Atom', x: 13, y: 49 }, { id: 'molecule', name: 'Molecule', x: 39, y: 49 }, { id: 'cell', name: 'Cell', x: 64, y: 49 }, { id: 'tissue', name: 'Tissue', x: 13, y: 91 }, { id: 'organ', name: 'Organ', x: 38, y: 91 }, { id: 'organ-system', name: 'Organ system', x: 64, y: 91 }, { id: 'organism', name: 'Organism', x: 87, y: 91 }] } },
  { id: 'diagram-cardiovascular-01', topic: 'cardiovascular', type: 'diagram', question: 'Drag each label onto the matching structure in the heart diagram.', explanation: 'The right side of the cutaway heart receives and pumps deoxygenated blood, while the left side receives and pumps oxygenated blood. The aorta leaves the left ventricle and the pulmonary trunk leaves the right ventricle.', diagram: { image: 'assets/test-diagrams/heart-anatomy-test.png', alt: 'Heart anatomy diagram for the test', labels: [{ id: 'aorta', name: 'Aorta', x: 86, y: 21 }, { id: 'superior-vena-cava', name: 'Superior vena cava', x: 55, y: 24 }, { id: 'right-atrium', name: 'Right atrium', x: 54, y: 50 }, { id: 'pulmonary-valve', name: 'Pulmonary valve', x: 52, y: 59 }, { id: 'right-ventricle', name: 'Right ventricle', x: 65, y: 94 }, { id: 'left-atrium', name: 'Left atrium', x: 94, y: 50 }, { id: 'mitral-valve', name: 'Mitral valve', x: 94, y: 62 }, { id: 'left-ventricle', name: 'Left ventricle', x: 92, y: 94 }] } },
  { id: 'diagram-respiratory-01', topic: 'respiratory', type: 'diagram', question: 'Drag each airway label onto the matching structure.', explanation: 'Air passes through the nasopharynx and mouth, down the trachea, through the bronchial tree and into the lungs. The diaphragm supports ventilation.', diagram: { image: 'assets/test-diagrams/respiratory-system-test.png', alt: 'Respiratory system diagram for the test', labels: [{ id: 'nasopharynx', name: 'Nasopharynx', x: 20, y: 11, targetWidth: 260, targetHeight: 58 }, { id: 'mouth', name: 'Mouth', x: 71, y: 21, targetWidth: 250, targetHeight: 58 }, { id: 'trachea', name: 'Trachea', x: 70, y: 41, targetWidth: 300, targetHeight: 150 }, { id: 'lungs', name: 'Lungs', x: 20, y: 41, targetWidth: 360, targetHeight: 90 }, { id: 'bronchial-tree', name: 'Bronchial tree', x: 18, y: 61, targetWidth: 380, targetHeight: 150 }, { id: 'diaphragm', name: 'Diaphragm', x: 68, y: 83, targetWidth: 440, targetHeight: 180 }] } },
  { id: 'diagram-nervous-01', topic: 'nervous', type: 'diagram', question: 'Drag the central and peripheral nervous system labels onto the diagram.', explanation: 'The central nervous system is the brain and spinal cord. The peripheral nervous system is the network of nerves outside them.', diagram: { image: 'assets/test-diagrams/nervous-system-test.png', alt: 'Central and peripheral nervous system diagram for the test', labels: [{ id: 'central', name: 'Central nervous system', x: 80, y: 9, targetWidth: 320, targetHeight: 180 }, { id: 'peripheral', name: 'Peripheral nervous system', x: 81, y: 68, targetWidth: 320, targetHeight: 180 }] } },
  { id: 'diagram-lymphatic-urinary-reproductive-01', topic: 'lymphatic-urinary-reproductive', type: 'diagram', question: 'Drag each label onto the matching structure in the combined systems diagram.', explanation: 'The kidneys filter blood and form urine, the bladder stores urine, and lymphatic vessels return excess tissue fluid to the circulation.', diagram: { image: 'assets/test-diagrams/lymphatic-urinary-reproductive-test.svg', alt: 'Lymphatic, urinary and reproductive systems diagram for the test', labels: [{ id: 'lymph-vessels', name: 'Lymphatic vessels', x: 13, y: 19, targetWidth: 270, targetHeight: 70 }, { id: 'kidneys', name: 'Kidneys', x: 79, y: 40 }, { id: 'bladder', name: 'Bladder', x: 77, y: 65 }, { id: 'reproductive-organs', name: 'Reproductive organs', x: 79, y: 90, targetWidth: 270, targetHeight: 70 }] } }
];

window.questionDatabase = questionDatabase;
